triage:
  first_ping_after_days: 0    # days to triage without reminder
  repeat_every_days: 0        # repeat reminder after X dats
  escalation_ping: 3          # on which reminder it will be escalated
  escalation_mentions:
    - "@bigcat88"
    - "@oleksandr-nc"

question:
  reminder_after_days: 0
  missing_info_label: "missing information"
  maintainers_allowlist:      # their comments DO NOT clear the label
    - "bigcat88"
