triage:
  first_ping_after_days: 7    # days to triage without reminder
  repeat_every_days: 7        # repeat reminder after X days
  escalation_ping: 3          # on which reminder it will be escalated
  escalation_mentions:
    - "@DaphneMuller"

question:
  reminder_after_days: 7      # days to remove "question" tag, and apply tag to mark issue as available to close.
  missing_info_label: "missing information"
  maintainers_allowlist:      # their comments DO NOT clear the label
    - "oleksandr-nc"
    - "kyteinsky"
    - "andrey18106"
