# .github/workflows/question-label-guard.yml
name: Auto-clear “question” when reporter replies

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  clear-if-needed:
    if: github.event.issue.state == 'open'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/read-yaml@v1
        id: cfg
        with:
          file: .github/issue-bot-config.yml
          property-path: question.maintainers_allowlist

      - name: Remove label if commenter is not allow-listed
        uses: actions/github-script@v7
        with:
          script: |
            const allow = JSON.parse(process.env.AL).map(s=>s.toLowerCase());
            const commenter = context.payload.comment.user.login.toLowerCase();
            if (allow.includes(commenter)) return;       // maintainer – keep label
            const labels = context.payload.issue.labels.map(l=>l.name);
            if (!labels.includes('question')) return;    // nothing to do
            await github.rest.issues.removeLabel({
              ...context.repo,
              issue_number: context.issue.number,
              name: 'question'
            });
            // also clean up question-reminded (if present)
            if (labels.includes('question-reminded')) {
              await github.rest.issues.removeLabel({
                ...context.repo,
                issue_number: context.issue.number,
                name: 'question-reminded'
              });
            }
        env:
          AL: ${{steps.cfg.outputs}}
