name: Auto-clear “question” & “missing information” when reporter replies

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  clear-labels:
    if: github.event.issue.state == 'open'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Read question config
        id: cfg
        uses: jbutcher5/read-yaml@1.6
        with:
          file: .github/issue-bot-config.yml
          key-path: '["question"]'

      - name: Remove labels if commenter not in allow-list
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const cfg = JSON.parse(process.env.CFG);
            const allow = cfg.maintainers_allowlist.map(u=>u.toLowerCase());
            const user  = context.payload.comment.user.login.toLowerCase();
            if (allow.includes(user)) return;

            const labels = context.payload.issue.labels.map(l=>l.name);
            const toRemove = [];
            if (labels.includes('question'))            toRemove.push('question');
            if (labels.includes('question-reminded'))   toRemove.push('question-reminded');
            if (labels.includes(cfg.missing_info_label)) toRemove.push(cfg.missing_info_label);

            for (const name of toRemove) {
              await github.rest.issues.removeLabel({
                ...context.repo,
                issue_number: context.issue.number,
                name
              }).catch(() => {});
            }
        env:
          CFG: ${{ steps.cfg.outputs.data }}
